### ISSUE TITLE
MultiSelectTreeView does not use template from ItemTemplateSelector

### ISSUE THREAD

**Issue by 7H3LaughingMan** [dg9ngf/MultiSelectTreeView#23]
I am trying to use a ItemTemplateSelector so that templates are chosen via coding. However, I am noticing that the actualy content from my template isn't being used, but it is working somewhat since if I remove the `ItemsSource="{Binding Children}"` from the template it not longer shows the children items. I am unable to do the templates in pure XAML since I have 50+ classes that extend from the `Event` class. I am able to use a ItemTemplateSelector with a normal TreeView just like this.

```
<local:ItemTemplateSelector x:Key="ItemTemplateSelector">
            <local:ItemTemplateSelector.EventTemplate>
                <HierarchicalDataTemplate ItemsSource="{Binding Children}">
                    <TextBlock Text="EventTemplate" />
                </HierarchicalDataTemplate>
            </local:ItemTemplateSelector.EventTemplate>
</local:ItemTemplateSelector>
```

```
<Controls:MultiSelectTreeView x:Name="tree" ItemsSource="{Binding Children}" DockPanel.Dock="Bottom" ItemTemplateSelector="{StaticResource ItemTemplateSelector}">
</Controls:MultiSelectTreeView>
```

```
public class ItemTemplateSelector : DataTemplateSelector
    {
        public DataTemplate EventTemplate { get; set; }

        public override DataTemplate SelectTemplate(object item, DependencyObject container)
        {
            System.Diagnostics.Debug.WriteLine(item.GetType());

            if (item is Event)
                return EventTemplate;

            return null;
        }
    }
```

**Comment by dg9ngf** [comment]
I've never used template selectors before, so could you provide me a test case application where I can investigate the issue?

**Comment by 7H3LaughingMan** [comment]
https://dl.dropboxusercontent.com/u/7231478/WPFTesting.zip

I copied the included Demo and made the necessary changes to show what I was talking about. You can also comment out the  `<Controls:MultiSelectTreeView.ItemContainerStyle>` section and switch it to a TreeView to show that it does work with a normal TreeView. I have included some Debug Output in `ItemTemplateSelector` and shows you that it is being called. You can also remove the `ItemsSource="{Binding Children}"` in the template it is using to see it is using the template somewhat to show the children.

**Comment by dg9ngf** [comment]
I can see the issue, but I'm sorry I don't know how to fix it. Maybe someone with TemplateSelector experience might know it? Could it be that TemplateSelector support requires additional coding and the WPF framework can't do it automatically? At least I can't find any code in the library that would refer to a template selector. If that's the case, I'd say that this control simply doesn't support using TemplateSelectors.

**Comment by 7H3LaughingMan** [comment]
Did some digging around and noticed there was another project that happened to have the same issue. Appears it was solved by editing the themes for the custom TreeViewItem. Already submitted a pull request with the necessary changes and it appears to work.

https://treeviewex.codeplex.com/SourceControl/changeset/72693

**Comment by dg9ngf** [comment]
Thank you for digging around and providing the fix. I have merged it into the repository and uploaded an updated NuGet package version.
