### ISSUE TITLE
Is Virtualizing working?

### ISSUE THREAD

**Issue by WiseWeasel** [dg9ngf/MultiSelectTreeView#25]
I'm unable to virtualize a MultiSelectTreeView.
I tried to add  `VirtualizingStackPanel.IsVirtualizing ="True" ScrollViewer.CanContentScroll="True"` in the demo XAML, without success.  Is Virtualization supported ? If yes, what is the procedure / code / restriction to add to make it work for the demo version?

**Comment by dg9ngf** [comment]
Virtualisation is not supported and it will cause a lot of pain to implement. It's not easy already for a flat list (done that, still only 99 % reliable), so I won't even start for a hierarchical tree. Whoever wants to try it is welcome to do that. I'm accepting pull requests for that but will do thorough tests. Don't forget keyboard navigation, just for a hint.
