### ISSUE TITLE
Is supported ContextMenu templates? 

### ISSUE THREAD

**Issue by juliomrqz** [dg9ngf/MultiSelectTreeView#26]
Hello.

Is possible to assign a ContextMenu template to a different tree view item?

Thanks.

**Comment by dg9ngf** [comment]
Can you please explain what you are trying to do?

**Comment by juliomrqz** [comment]
For example, in the MultiSelectTreeView demo, can you have different context menus for the objects ColorItemViewModel and TreeItemViewModel using a template?

**Comment by dg9ngf** [comment]
Hm, I use a single context menu and show/hide or enable/disable the menu items based on the tree items selection. This also allows you to react on multiple selected items of different types, if that's allowed. Would that be a solution for you?

**Comment by juliomrqz** [comment]
I think that is a better solution. Thank you very much.
