### ISSUE TITLE
Treeview disposed on tabhide

### ISSUE THREAD

**Issue by tevert** [dg9ngf/MultiSelectTreeView#28]
We have a MultiSelectTreeView inside a TabItem, and we've found that switching to another tab triggers the Unload event on the control (MultiSelectTreeView.cs:688). This in turn calls a series of dispose events which ultimately result in unsubscribing the mouse event handlers (BorderSelectionLogic.cs:67), which kills the drag-selecting. 

It looks like this code is inherited from the original TreeViewEx, but it also seems to have been removed from that code base at some point. I recommend the same here.

**Comment by dg9ngf** [comment]
Changed in 1e8a18e6, can you please verify the fix?

**Comment by dg9ngf** [comment]
Sorry, there was a problem with it. Please use 6ecee8f4.

**Comment by tevert** [comment]
Yep, this does it, thanks!

**Comment by dg9ngf** [comment]
Alright. Thank you for the report and investigation! TreeViewEx has indeed changed a lot. And also due to my improvements, large parts of the code have been altered and don't look similar anymore.
