### ISSUE TITLE
Aero shading border

### ISSUE THREAD

**Issue by tevert** [dg9ngf/MultiSelectTreeView#29]
https://github.com/dg9ngf/MultiSelectTreeView/blob/master/MultiSelectTreeView/Themes/MultiSelectTreeViewItem.Aero.xaml#L224

I was wondering what controls this border's appearance. Currently, in the demo project, it appears to only affect the last selected treeview item (which is no longer selected). In our project, that border is always on and we can't style it away, so we're wondering if there's a property or something that's toggling it. 

We've also noticed that it was removed for the Aero2 (Windows 8) theme. Is there a way to just force that theme to be loaded instead?

**Comment by dg9ngf** [comment]
This border is part of the Aero (as in Vista/Win7) design. It's there intentionally and cannot be styled away other than replacing the entire style. That's how XAML works. XAML will also select the appropriate theme based on the current system theme. I don't know whether this can be force-changed. Please look elsewhere for that information.

**Comment by tevert** [comment]
Yes, we ended up just replacing the whole style. Thanks anyway though!
