### ISSUE TITLE
IsSelected changed doesn't cause child item to come into view

### ISSUE THREAD

**Issue by dmgores** [dg9ngf/MultiSelectTreeView#32]
If you have an item that is a child, and near the end of a long list of children that is out of scroll view when the parent is expanded...

If you change the item's IsSelected to true, then the item doesn't scroll into view.

To fix this I added this line:
"item.Dispatcher.BeginInvoke((Action)(() => FocusHelper.Focus(item, true)), Threading.DispatcherPriority.Input);"

Right after:
"item.ParentTreeView.SelectedItems.Add(item.DataContext);"

In the method MultiSelectTreeViewItem.OnIsSelectedChanged

If I don't use the BeginInvoke, then the scroll into view doesn't work in the case where the parent wasn't expanded.

**Comment by dg9ngf** [comment]
I'm not sure this is a bug. When you set `IsSelected = true` on many items, the view would wildly scroll around. If you mean to bring an item into view (not only change its state to selected – which BTW does not mean it's focused!) you can call `MultiSelectTreeView.FocusItem(item, true)`.

**Comment by dmgores** [comment]
Oh, good call.  I can do it that way thanks.
